#!/usr/bin/env python3
"""
生成《生日快乐》PCM音频数据，导出为Arduino C头文件
用法: python3 generate_birthday_pcm.py
输出: birthday_pcm.h (放到Arduino项目同一目录)
"""

import math
import struct

SAMPLE_RATE = 16000  # 采样率
BITS = 16            # 位深

def generate_note(freq, duration_ms, amp=0.5, decay=8.0, bass_freq=None):
    """
    生成带指数衰减包络的方波音符
    freq: 旋律音频率
    duration_ms: 时长(毫秒)
    amp: 振幅 (0.0~1.0)
    decay: 衰减系数，越大衰减越快
    bass_freq: 低音根音频率(和声)，None表示不加低音
    """
    num_samples = int(SAMPLE_RATE * duration_ms / 1000)
    samples = []
    max_amp = int(32767 * amp)

    for n in range(num_samples):
        t = n / SAMPLE_RATE

        # 方波旋律音 (基频 + 少量3次/5次谐波增加厚度)
        phase = 2.0 * math.pi * freq * t
        melody = 0.7 * (1.0 if math.sin(phase) >= 0 else -1.0)
        melody += 0.2 * (1.0 if math.sin(3.0 * phase) >= 0 else -1.0)
        melody += 0.1 * (1.0 if math.sin(5.0 * phase) >= 0 else -1.0)

        # 低音和声 (正弦波，更柔和)
        bass = 0.0
        if bass_freq:
            bass = 0.6 * math.sin(2.0 * math.pi * bass_freq * t)

        # 叠加
        val = melody + bass

        # 指数衰减包络 (ADSR中的Decay)
        envelope = math.exp(-t * decay)
        if t < 0.01:  # Attack: 前10ms快速起音
            envelope *= (t / 0.01)

        # 转为16位有符号整数
        sample = int(val * max_amp * envelope)
        # 限幅保护
        sample = max(-32768, min(32767, sample))
        samples.append(sample)

    return samples

def generate_silence(duration_ms):
    """生成静音"""
    num_samples = int(SAMPLE_RATE * duration_ms / 1000)
    return [0] * num_samples

def main():
    # 音符频率表 (C调)
    notes = {
        'C4': 262, 'D4': 294, 'E4': 330, 'F4': 349,
        'G4': 392, 'A4': 440, 'B4': 494,
        'C5': 523, 'D5': 587, 'E5': 659, 'F5': 698, 'G5': 784,
    }

    # 和弦根音映射
    chords = {
        'G': 196,   # G3
        'C': 262,   # C4
        'D7': 294,  # D4 (简化用D代替D7)
    }

    # 《生日快乐》旋律编排: [(音符, 和弦, 时长ms), ...]
    # 节奏: 八=250ms, 四=500ms, 四附点=750ms
    EIGHTH = 250
    QUARTER = 500
    DOT_QUARTER = 750

    score = [
        # 第一句: 祝你生日快乐 (G和弦)
        ('G4', 'G', EIGHTH),
        ('G4', 'G', EIGHTH),
        ('A4', 'G', QUARTER),
        ('G4', 'G', QUARTER),
        ('C5', 'C', DOT_QUARTER),
        ('B4', 'G', EIGHTH),

        # 第二句: 祝你生日快乐 (G -> D7)
        ('G4', 'G', EIGHTH),
        ('G4', 'G', EIGHTH),
        ('A4', 'G', QUARTER),
        ('G4', 'G', QUARTER),
        ('D5', 'D7', DOT_QUARTER),
        ('C5', 'C', EIGHTH),

        # 第三句: 祝你生日快乐 (G -> C)
        ('G4', 'G', EIGHTH),
        ('G4', 'G', EIGHTH),
        ('G5', 'C', QUARTER),
        ('E5', 'C', QUARTER),
        ('C5', 'G', QUARTER),
        ('B4', 'D7', QUARTER),
        ('A4', 'G', QUARTER),

        # 第四句: 祝你生日快乐 (C -> D7 -> G)
        ('F5', 'C', EIGHTH),
        ('F5', 'C', EIGHTH),
        ('E5', 'G', QUARTER),
        ('C5', 'C', QUARTER),
        ('D5', 'D7', DOT_QUARTER),
        ('C5', 'G', EIGHTH),
    ]

    # 生成PCM数据
    all_samples = []
    for note_name, chord_name, duration in score:
        freq = notes[note_name]
        bass = chords[chord_name]
        samples = generate_note(freq, duration, amp=0.6, decay=6.0, bass_freq=bass)
        all_samples.extend(samples)
        # 音符之间加20ms休止
        all_samples.extend(generate_silence(20))

    # 结尾加1秒静音
    all_samples.extend(generate_silence(1000))

    # 导出为C头文件
    output_path = "/Users/kun.li/Code/LingxiGlove/src/tests/test_speaker/birthday_pcm.h"
    with open(output_path, 'w') as f:
        f.write("// Auto-generated by generate_birthday_pcm.py\n")
        f.write("// Happy Birthday PCM data: 16kHz, 16bit, mono\n\n")
        f.write("#ifndef BIRTHDAY_PCM_H\n")
        f.write("#define BIRTHDAY_PCM_H\n\n")
        f.write(f"const size_t BIRTHDAY_PCM_LEN = {len(all_samples) * 2};\n\n")
        f.write("const uint8_t BIRTHDAY_PCM[] = {\n  ")

        # 将16位样本拆分为两个字节 (小端序)
        byte_count = 0
        for sample in all_samples:
            # 16位有符号转无符号字节对
            usample = sample & 0xFFFF
            low = usample & 0xFF
            high = (usample >> 8) & 0xFF
            f.write(f"0x{low:02X}, 0x{high:02X}, ")
            byte_count += 2
            if byte_count % 32 == 0:  # 每行32字节换行
                f.write("\n  ")

        f.write("\n};\n\n")
        f.write("#endif // BIRTHDAY_PCM_H\n")

    total_seconds = len(all_samples) / SAMPLE_RATE
    print(f"生成完成: {output_path}")
    print(f"样本数: {len(all_samples)}")
    print(f"数据大小: {len(all_samples) * 2} bytes ({len(all_samples) * 2 / 1024:.1f} KB)")
    print(f"时长: {total_seconds:.1f} seconds")

    # 同时生成一个WAV文件方便用户在电脑上试听
    wav_path = "/Users/kun.li/Code/LingxiGlove/src/tests/test_speaker/birthday.wav"
    with open(wav_path, 'wb') as f:
        # WAV header (44 bytes)
        num_channels = 1
        byte_rate = SAMPLE_RATE * num_channels * 2
        block_align = num_channels * 2
        data_size = len(all_samples) * 2

        f.write(b'RIFF')
        f.write(struct.pack('<I', 36 + data_size))
        f.write(b'WAVE')
        f.write(b'fmt ')
        f.write(struct.pack('<I', 16))          # Subchunk1Size
        f.write(struct.pack('<H', 1))           # AudioFormat (PCM)
        f.write(struct.pack('<H', num_channels))
        f.write(struct.pack('<I', SAMPLE_RATE))
        f.write(struct.pack('<I', byte_rate))
        f.write(struct.pack('<H', block_align))
        f.write(struct.pack('<H', 16))          # BitsPerSample
        f.write(b'data')
        f.write(struct.pack('<I', data_size))

        # PCM data
        for sample in all_samples:
            f.write(struct.pack('<h', sample))

    print(f"WAV文件: {wav_path} (可用电脑播放器试听)")

if __name__ == '__main__':
    main()
