#!/usr/bin/env python3
"""
一键生成中文语音并转为Arduino PCM代码
用法: python3 generate_voice.py "你好，我是灵犀手套"
"""

import sys
import os
import asyncio
from pydub import AudioSegment

try:
    import edge_tts
except ImportError:
    print("请先安装 edge-tts: pip3 install edge-tts")
    sys.exit(1)

# 中文女声 (微软晓晓，音质较好)
VOICE = "zh-CN-XiaoxiaoNeural"
SAMPLE_RATE = 16000

async def generate_tts(text, output_mp3):
    """用edge-tts生成语音MP3"""
    print(f"[TTS] 正在生成语音: \"{text}\"")
    communicate = edge_tts.Communicate(text, VOICE)
    await communicate.save(output_mp3)
    print(f"[TTS] MP3已保存: {output_mp3}")

def mp3_to_arduino_pcm(mp3_file, output_h, text, var_name="AUDIO_PCM"):
    """将MP3转为Arduino可用的PCM头文件"""
    print(f"[转换] 处理音频: {mp3_file}")

    # 加载MP3
    audio = AudioSegment.from_mp3(mp3_file)

    # 转为16kHz、单声道、16bit
    audio = audio.set_frame_rate(SAMPLE_RATE).set_channels(1).set_sample_width(2)

    # 获取原始PCM数据
    pcm_data = audio.raw_data
    pcm_len = len(pcm_data)

    print(f"[转换] 时长: {len(audio)/1000:.1f}秒")
    print(f"[转换] PCM大小: {pcm_len} bytes ({pcm_len/1024:.1f} KB)")

    # 生成C头文件
    with open(output_h, 'w') as f:
        f.write(f"// Auto-generated by generate_voice.py\n")
        f.write(f"// Text: \"{text}\"\n")
        f.write(f"// Voice: {VOICE}\n")
        f.write(f"// Format: {SAMPLE_RATE}Hz, 16bit, mono\n\n")
        f.write(f"#ifndef {var_name}_H\n")
        f.write(f"#define {var_name}_H\n\n")
        f.write(f"const size_t {var_name}_LEN = {pcm_len};\n\n")
        f.write(f"const uint8_t {var_name}[] = {{\n  ")

        byte_count = 0
        for i in range(0, pcm_len, 2):
            # 小端序16位样本
            sample = pcm_data[i] | (pcm_data[i+1] << 8)
            low = sample & 0xFF
            high = (sample >> 8) & 0xFF
            f.write(f"0x{low:02X}, 0x{high:02X}, ")
            byte_count += 2
            if byte_count % 32 == 0:
                f.write("\n  ")

        f.write("\n};\n\n")
        f.write(f"#endif // {var_name}_H\n")

    print(f"[完成] Arduino头文件: {output_h}")

async def main():
    # 获取要合成的文字
    if len(sys.argv) > 1:
        text = sys.argv[1]
    else:
        text = "你好，我是灵犀手套"

    output_dir = "/Users/kun.li/Code/LingxiGlove/src/tests/test_speaker"
    mp3_file = os.path.join(output_dir, "voice_temp.mp3")
    h_file = os.path.join(output_dir, "voice_pcm.h")

    # 生成TTS
    await generate_tts(text, mp3_file)

    # 转为Arduino PCM
    mp3_to_arduino_pcm(mp3_file, h_file, text)

    # 清理临时MP3
    if os.path.exists(mp3_file):
        os.remove(mp3_file)
        print(f"[清理] 已删除临时文件: {mp3_file}")

    print("\n下一步:")
    print(f"  1. 确认 voice_pcm.h 和 test_speaker.ino 在同一文件夹")
    print(f"  2. 上传 test_speaker.ino 到ESP32-S3")
    print(f"  3. 打开串口监视器听效果")

if __name__ == '__main__':
    asyncio.run(main())
